services:
  - type: web
    name: verity
    runtime: static
    staticPublishPath: .
    branch: main
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
